# Generated by Django 3.0.3 on 2020-05-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('bed_no', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('Gender', models.CharField(max_length=3)),
                ('prev_dess', models.CharField(default='None', max_length=100)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
    ]
