# Generated by Django 3.0.3 on 2020-05-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='lab_id',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
