# Generated by Django 3.0.3 on 2020-05-14 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_patients_admit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='state',
            field=models.CharField(default='Uttrakhand', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patients',
            name='admit_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 8, 17, 35, 817473)),
        ),
    ]
