# Generated by Django 3.0.3 on 2020-05-14 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200514_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='XRayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_no', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 5, 14, 13, 56, 3, 483270))),
            ],
        ),
        migrations.AlterField(
            model_name='patients',
            name='admit_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 13, 56, 3, 483270)),
        ),
    ]
