# Generated by Django 3.0.3 on 2020-05-14 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200514_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='xraydata',
            name='accuracy',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patients',
            name='admit_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 15, 47, 49, 28878)),
        ),
        migrations.AlterField(
            model_name='xraydata',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 15, 47, 49, 29875)),
        ),
    ]
