# Generated by Django 3.0.3 on 2020-05-14 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200514_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='admit_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 15, 52, 49, 398732)),
        ),
        migrations.AlterField(
            model_name='xraydata',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 15, 52, 49, 399730)),
        ),
    ]
