# Generated by Django 3.0.3 on 2020-05-14 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200514_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='xraydata',
            name='img',
            field=models.ImageField(default=1, upload_to='x_ray_data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patients',
            name='admit_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 15, 53, 30, 522739)),
        ),
        migrations.AlterField(
            model_name='xraydata',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 15, 53, 30, 522739)),
        ),
    ]
